export const FETCH_PROPERTY_START = "FETCH_PROPERTY_START";
export const FETCH_PROPERTY_FAILED = "FETCH_PROPERTY_FAILED";

export const FETCH_PROPERTY_SUCCEEDED = "FETCH_PROPERTY_SUCCEEDED";
export const FETCH_PROPERTY_BYID_SUCCEEDED = "FETCH_PROPERTY_BYID_SUCCEEDED";
export const ADD_PROPERTY = "ADD_PROPERTY";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
